---
name: Build test
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.env) }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - { CC: "gcc" }
          - { CC: "gcc", ASAN_UBSAN: "true" }
          - { CC: "clang" }
          - { CC: "clang", ASAN_UBSAN: "true" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - run: sudo -E .github/workflows/build.sh install-build-deps
      - run: sudo -E .github/workflows/build.sh build
  coveralls:
    if: github.repository == 'evverx/avahi'
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      checks: write
    env:
      CC: "gcc"
      COVERAGE: "true"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - run: sudo -E .github/workflows/build.sh install-build-deps
      - run: sudo -E .github/workflows/build.sh build
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.info
