---
name: Build test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  bsd:
    runs-on: ubuntu-26.04
    defaults:
      run:
        shell: cpa.sh {0} --sync-files runner-to-vm
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.version }}-${{ toJSON(matrix.env) }}-${{ github.ref }}-bsd
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: ['freebsd']
        version: ['14.5', '15.1']
        env:
          - { CC: "clang", ASAN_UBSAN: "false", DISTCHECK: "true" }
          - { CC: "clang", ASAN_UBSAN: "true", DISTCHECK: "false" }
          - { CC: "clang", ASAN_UBSAN: "false", VALGRIND: "true" }
        include:
          - os: 'netbsd'
            version: '10.1'
            env: { CC: "gcc" }
          - os: 'netbsd'
            version: '10.1'
            env: { CC: "clang", ASAN_UBSAN: "true" }
          - os: 'netbsd'
            version: '11.0'
            env: { CC: "gcc" }
          - os: 'netbsd'
            version: '11.0'
            env: { CC: "clang", ASAN_UBSAN: "true" }
          - os: 'omnios'
            version: 'r151058'
            env: { CC: "gcc" }
          - os: 'openbsd'
            version: '7.9'
            env: { CC: "clang" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Start VM
        uses: cross-platform-actions/action@e0b9770014ba65d5e0815f15b74031c3a635f641 # v1.6.0
        with:
          operating_system: ${{ matrix.os }}
          version: ${{ matrix.version }}
          architecture: 'x86_64'
          environment_variables: ASAN_UBSAN CC DISTCHECK VALGRIND
      - name: Run commands
        run: |
          sudo -E .github/workflows/build.sh install-build-deps-${{ matrix.os }}
          sudo -E .github/workflows/build.sh build
